disabled_rules:
  - line_length
  - trailing_whitespace

opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newline
  - empty_count
  - explicit_init
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - let_var_whitespace
  - operator_usage_whitespace
  - overridden_super_call
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - return_arrow_whitespace
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - unused_setter_value
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

excluded:
  - Carthage
  - Pods
  - build/
  - .build/
  - Example/Pods
  - Example/build/

trailing_comma:
  mandatory_comma: true

identifier_name:
  min_length: 2
  max_length: 60

type_name:
  min_length: 2
  max_length: 60

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 50
  error: 100

cyclomatic_complexity:
  warning: 10
  error: 20

large_tuple:
  warning: 3
  error: 5

nesting:
  type_level:
    warning: 2
    error: 3
  function_level:
    warning: 3
    error: 5